# Generated by Django 5.2.1 on 2025-06-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_alter_plan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
