# Generated by Django 5.2.1 on 2025-06-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_client_first_name_client_last_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
